version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: flight-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
  wiremock:
    image: wiremock/wiremock:latest
    container_name: flight-mock
    ports:
      - "8081:8081"
    volumes:
      - ./mock:/home/mock
    command: ["--global-response-templating"]

volumes:
  redis-data:
  mock: